#spring:
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://192.168.56.10:3306/mall-ums?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.cj.jdbc.Driver #mysql版本8.0以上才需要该驱动
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  application:
#    name: mall-member
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml #classpath*代表扫描所有类路径下的xml文件
#  global-config:
#    db-config:
#      id-type: auto #设置主键自增策略
#server:
#  port: 8020